Repository liquidmetal-dev/flintlock, pull requests merged in 2021-12, with the labels that each got.

#301 refactor: introduce a client package
  client/cloudinit/metadata.go
  client/cloudinit/network.go
  client/cloudinit/userdata.go
  client/go.mod
  go.mod
  infrastructure/firecracker/config.go
Labels: kind/refactor

#295 Make sure a mvm is properly stopped
  infrastructure/firecracker/provider.go
  internal/command/run/run.go
  internal/config/config.go
  pkg/defaults/defaults.go
  pkg/process/process.go
  pkg/process/process_test.go
Labels: kind/feature

#304 chore(deps): Add action to bump version of firecracker in e2es
  .github/workflows/fork.yaml
  hack/scripts/bootstrap.sh
  hack/scripts/bump_firecracker.sh
Labels: kind/feature, area/testing, size/s, area/firecracker

#260 feat: static ip and ipv6 changes
  .golangci.yml
  api/services/microvm/v1alpha1/microvms.swagger.json
  api/types/microvm.pb.go
  api/types/microvm.proto
  client/cloudinit/network.go
  core/models/network.go
  core/models/network_test.go
  infrastructure/firecracker/config.go
  infrastructure/grpc/convert.go
  infrastructure/grpc/defaults.go
  pkg/validation/validate_test.go
  userdocs/docs/grpc/types/proto.md
Labels: kind/feature

#316 refactor: cloudinit pointer removal
  client/cloudinit/doc.go
  client/cloudinit/metadata.go
  client/cloudinit/network.go
  client/cloudinit/userdata.go
  infrastructure/firecracker/config.go
Labels: kind/refactor

#318 Use single quotes to compare var in action
  .github/workflows/fork.yaml
Labels: kind/bug, size/xs

#322 feat: added `DELETING` microvm status
  api/services/microvm/v1alpha1/microvms.swagger.json
  api/types/microvm.pb.go
  api/types/microvm.proto
  core/application/app_test.go
  core/application/commands.go
  core/models/microvm.go
  go.mod
  go.sum
  infrastructure/grpc/convert.go
  userdocs/docs/grpc/types/proto.md
Labels: kind/feature, area/api

#315 Set MVM state to 'created' only on plan success
  core/application/reconcile.go
  core/models/microvm.go
  core/plans/microvm_create_update.go
  core/plans/microvm_create_update_test.go
  core/plans/microvm_delete.go
  core/ports/services.go
  infrastructure/grpc/convert.go
  pkg/planner/actuator_test.go
  pkg/planner/planner.go
Labels: kind/bug

#308 feat: remove option to set volume snapshotter
  infrastructure/containerd/config.go
  internal/command/flags/flags.go
  internal/config/config.go
  internal/inject/wire.go
  internal/inject/wire_gen.go
  pkg/defaults/defaults.go
Labels: kind/feature

#321 chore(test): Get only first output from create func
  test/tools/run.py
Labels: kind/bug

#319 Add json tags on cloudinit Metadata
  client/cloudinit/metadata.go
Labels: kind/cleanup

#329 refector: remove pause/result from provider interface
  Makefile
  core/ports/services.go
  core/steps/microvm/create_test.go
  core/steps/microvm/delete_test.go
  core/steps/microvm/start_test.go
  go.mod
  go.sum
  infrastructure/firecracker/provider.go
  infrastructure/mock/ports.go
Labels: kind/refactor

#324 Add service file for systemd
  flintlockd.service
Labels: kind/feature

#335 feat: provisioning script
  docs/quick-start.md
  hack/scripts/README.md
  hack/scripts/provision.sh
Labels: kind/feature
