Repository liquidmetal-dev/flintlock, pull requests merged in 2021-11, with the labels that each got.

#187 Add initial E2E tests [running locally]
  .github/workflows/nightly_e2e.yml
  Makefile
  go.mod
  go.sum
  hack/scripts/bootstrap.sh
  hack/scripts/devpool.sh
  test/docker/Dockerfile.e2e
  test/docker/entrypoint.sh
  test/e2e/e2e_test.go
  test/e2e/infra/.gitignore
  test/e2e/infra/files/get-meta.sh
  test/e2e/infra/main.tf
  test/e2e/infra/metal.py
  test/e2e/infra/output.tf
  test/e2e/utils/runner.go
  test/e2e/utils/utils.go
Labels: kind/feature, area/testing

#184 Ability to query older versions of a vmspec
  core/application/app_test.go
  core/application/commands.go
  core/application/query.go
  core/application/reconcile.go
  core/errors/errors.go
  core/ports/repositories.go
  go.mod
  go.sum
  infrastructure/containerd/repo.go
  infrastructure/containerd/repo_test.go
  infrastructure/mock/mock.go
Labels: kind/feature

#197 feat: add version subcommand
  internal/command/gw/gw.go
  internal/command/root.go
  internal/command/run/run.go
  internal/version/version.go
Labels: kind/feature, size/s

#196 security: Update indirect dependency: mongo-driver
  go.mod
  go.sum
Labels: size/xs, kind/cleanup, area/dependency

#200 chore: remove the message on XL pr
  .github/workflows/pr_size.yml
Labels: size/xs, kind/cleanup

#199 Add python tool for testing against Equinix
  Makefile
  hack/scripts/bootstrap.sh
  hack/scripts/devpool.sh
  hack/tools/.gitignore
  test/e2e/infra/metal.py
  test/tools/.gitignore
  test/tools/README.md
  test/tools/metal.py
  test/tools/requirements.txt
  test/tools/run.py
  test/tools/test.py
  test/tools/userdata.sh
Labels: kind/feature, area/build-and-release

#195 docs: user documentation on github pages
  .github/workflows/deploy-docs.yaml
  Makefile
  README.md
  api/types/microvm.pb.go
  api/types/microvm.proto
  buf.gen.yaml
  buf.yaml
  docs/adr/0004-merge-create-and-update-plan.md
  docs/quick-start.md
  hack/tools/go.mod
  hack/tools/go.sum
  userdocs/.gitignore
  userdocs/README.md
  userdocs/babel.config.js
  userdocs/blog/2021-11-02-v0.1.0-alpha.1.md
  userdocs/blog/2021-11-02-welcome/diagram-1.png
  userdocs/blog/2021-11-02-welcome/index.md
  userdocs/blog/authors.yml
  userdocs/docs/getting-started/basics/_category_.json
  userdocs/docs/getting-started/basics/configuring-network.md
  userdocs/docs/getting-started/basics/containerd.md
  userdocs/docs/getting-started/basics/interacting-with-the-service.md
  userdocs/docs/getting-started/basics/set-up-and-start-flintlock.md
  userdocs/docs/getting-started/basics/set-up-firecracker.md
  userdocs/docs/getting-started/extras/_category_.json
  userdocs/docs/getting-started/extras/image-creation.md
  userdocs/docs/getting-started/extras/use-vagrant.md
  userdocs/docs/getting-started/troubleshooting/_category_.json
  userdocs/docs/getting-started/troubleshooting/failed-to-reconcile-vmid.md
  userdocs/docs/grpc/services/microvm/v1alpha1/proto.md
  userdocs/docs/grpc/types/proto.md
  userdocs/docs/intro.md
  userdocs/docs/proto.md
  userdocs/docusaurus.config.js
  userdocs/package-lock.json
  userdocs/package.json
  userdocs/sidebars.js
  userdocs/src/components/HomepageFeatures.js
  userdocs/src/components/HomepageFeatures.module.css
  userdocs/src/css/custom.css
  userdocs/src/pages/index.js
  userdocs/src/pages/index.module.css
  userdocs/static/.nojekyll
  userdocs/static/CNAME
  userdocs/static/img/docusaurus.png
  userdocs/static/img/favicon.ico
  userdocs/static/img/logo.svg
  userdocs/static/img/tutorial/docsVersionDropdown.png
  userdocs/static/img/tutorial/localeDropdown.png
  userdocs/static/img/undraw_docusaurus_mountain.svg
  userdocs/static/img/undraw_docusaurus_react.svg
  userdocs/static/img/undraw_docusaurus_tree.svg
  userdocs/yarn.lock
Labels: kind/documentation, size/xl

#201 Update the nightly e2e workflow
  .github/workflows/nightly_e2e.yml
Labels: kind/feature, size/xs

#216 Ensure that test failures cause CI failure
  test/tools/metal.py
  test/tools/test.py
Labels: kind/bug

#217 Format link in slack message correctly
  .github/workflows/nightly_e2e.yml
Labels: kind/bug, size/xs

#212 chore(security): Run CodeQL scan on PRs and on schedule
  .github/workflows/codeql-analysis.yml
Labels: kind/feature, area/security

#220 Disable root volume validation
  hack/scripts/payload/CreateMicroVM.json
  pkg/validation/validate.go
  pkg/validation/validate_test.go
  test/e2e/utils/utils.go
Labels: kind/bug

#221 fix: ensure create plan is executed once
  core/plans/microvm_create_update.go
  core/plans/microvm_delete.go
  core/steps/microvm/create.go
  core/steps/microvm/start.go
Labels: kind/bug

#222 refactor: remove update gRPC enpoint and usecase implementation
  README.md
  api/services/microvm/v1alpha1/microvms.pb.go
  api/services/microvm/v1alpha1/microvms.pb.gw.go
  api/services/microvm/v1alpha1/microvms.proto
  api/services/microvm/v1alpha1/microvms.swagger.json
  api/services/microvm/v1alpha1/microvms_grpc.pb.go
  core/application/app_test.go
  core/application/commands.go
  core/plans/microvm_create_update.go
  core/ports/usecases.go
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
  hack/tools/tools.go
  infrastructure/grpc/server.go
  userdocs/docs/grpc/services/microvm/v1alpha1/proto.md
Labels: area/api, size/m, kind/refactor

#223 refactor: move thinpool setup to general test Setup/Teardown
  Makefile
  go.mod
  go.sum
  test/docker/Dockerfile.e2e
  test/docker/entrypoint.sh
  test/e2e/utils/runner.go
  test/tools/metal.py
  test/tools/userdata.sh
Labels: kind/feature, size/m

#226 feat: Use random generated device name for ifaces
  core/models/network.go
  core/plans/helper_test.go
  core/plans/matcher_test.go
  core/plans/microvm_create_update_test.go
  core/plans/microvm_delete.go
  core/plans/microvm_delete_test.go
  core/steps/network/const.go
  core/steps/network/info.go
  core/steps/network/interface_create.go
  core/steps/network/interface_create_test.go
  core/steps/network/interface_delete.go
  core/steps/network/interface_delete_test.go
  core/steps/network/matcher_test.go
  docs/adr/0005-network-device-name.md
  infrastructure/containerd/event_service_test.go
  infrastructure/grpc/convert.go
  infrastructure/network/errors.go
  infrastructure/network/network_service.go
  infrastructure/network/utils.go
  infrastructure/network/utils_test.go
  pkg/planner/actuator.go
Labels: kind/feature

#228 feat: add developer docs
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  CONTRIBUTING.md
  LICENSE
  README.md
Labels: kind/documentation

#247 fix: Makefile regexp for help
  Makefile
Labels: kind/bug

#231 fix: set mac address for macvtap if specified
  core/steps/network/interface_create.go
  infrastructure/network/network_service.go
Labels: kind/bug

#238 chore(fmt): Enable disabled linters in global scope
  .github/workflows/lint.yml
  .golangci.yml
  cmd/dev-helper/main.go
  core/application/commands.go
  core/application/reconcile.go
  core/models/network.go
  core/models/vmid.go
  core/models/volumes.go
  core/plans/microvm_create_update.go
  core/plans/microvm_delete.go
  core/plans/types.go
  core/steps/microvm/create.go
  core/steps/microvm/delete.go
  core/steps/network/interface_create.go
  core/steps/network/interface_delete.go
  core/steps/runtime/dir_create.go
  core/steps/runtime/dir_delete.go
  core/steps/runtime/initrd_mount.go
  core/steps/runtime/kernel_mount.go
  core/steps/runtime/volume_mount.go
  docs/adr/0005-network-device-name.md
  docs/adr/0246-linters.md
  hack/tools/go.mod
  hack/tools/go.sum
  infrastructure/containerd/content.go
  infrastructure/containerd/convert.go
  infrastructure/containerd/event_service.go
  infrastructure/containerd/image_service.go
  infrastructure/containerd/lease.go
  infrastructure/containerd/repo.go
  infrastructure/containerd/snapshot.go
  infrastructure/controllers/microvm_controller.go
  infrastructure/firecracker/config.go
  infrastructure/firecracker/create.go
  infrastructure/firecracker/provider.go
  infrastructure/firecracker/state.go
  infrastructure/firecracker/types.go
  infrastructure/grpc/convert.go
  infrastructure/grpc/server.go
  infrastructure/network/network_service.go
  infrastructure/network/utils.go
  infrastructure/ulid/ulid.go
  internal/command/flags/flags.go
  internal/command/gw/gw.go
  internal/command/root.go
  internal/command/run/run.go
  pkg/flags/flags.go
  pkg/log/log.go
  pkg/planner/actuator.go
  pkg/queue/queue.go
  pkg/validation/validate.go
  pkg/wait/wait.go
  test/e2e/utils/runner.go
Labels: kind/cleanup

#239 chore(test): Add configurable opts to e2e tests
  .github/workflows/nightly_e2e.yml
  CONTRIBUTING.md
  test/e2e/README.md
  test/e2e/e2e_test.go
  test/e2e/utils/params.go
  test/e2e/utils/runner.go
Labels: kind/feature

#251 Disable Documentation site publish if it's a forked repo
  .github/workflows/deploy-docs.yaml
Labels: kind/cleanup

#252 docs: add adr to provide no support for in-place microvm updates
  docs/adr/0234-update-api.md
Labels: kind/documentation, size/xs

#254 Run the e2es as part of the release process
  .github/workflows/release.yml
  docs/releasing.md
Labels: kind/feature

#249 chore(test): Add config file option to e2e metal tooling
  Makefile
  test/e2e/README.md
  test/e2e/test.sh
  test/tools/README.md
  test/tools/config.py
  test/tools/example-config.yaml
  test/tools/metal.py
  test/tools/requirements.txt
  test/tools/run.py
  test/tools/schema.yaml
  test/tools/test.py
Labels: kind/feature

#256 Fix tabbing in release workflow
  .github/workflows/release.yml
Labels: kind/bug

#257 Fix tabbing in release workflow again
  .github/workflows/release.yml
Labels: kind/bug

#262 docs: add ADR for opinionated API changes
  docs/adr/0241-opinionated-api-changes.md
Labels: kind/documentation, area/api, size/s

#263 chore(test): Tidy up python tool
  test/tools/config/__init__.py
  test/tools/config/config.py
  test/tools/config/schema.yaml
  test/tools/config/userdata.sh
  test/tools/metal/__init__.py
  test/tools/metal/welder.py
  test/tools/run.py
  test/tools/test/__init__.py
  test/tools/test/runner.py
Labels: kind/bug

#265 feat: Add script to setup direct-lvm mode for containerd
  docs/quick-start.md
  hack/scripts/devpool.sh
  hack/scripts/direct_lvm.sh
  test/tools/config/config.py
Labels: kind/feature

#270 feat(test): Wire e2e tests to use direct lvm thinpool for containerd
  test/e2e/README.md
  test/e2e/utils/params.go
  test/e2e/utils/runner.go
  test/tools/config/config.py
  test/tools/config/schema.yaml
  test/tools/example-config.yaml
  test/tools/test/runner.py
Labels: kind/feature, size/s

#272 feat(test): Check capacity of facility before creating device
  test/tools/config/config.py
  test/tools/config/schema.yaml
  test/tools/example-config.yaml
  test/tools/metal/error.py
  test/tools/metal/welder.py
  test/tools/run.py
Labels: kind/feature

#273 feat(test): Add opts to configure repo and branch
  .github/workflows/nightly_e2e.yml
  test/tools/config/config.py
  test/tools/config/schema.yaml
  test/tools/config/userdata.sh
  test/tools/example-config.yaml
Labels: kind/feature, size/s

#255 feat: Add retry counter on failed reconciliation
  core/application/reconcile.go
  core/errors/errors.go
  core/models/microvm.go
  core/plans/const.go
  core/plans/microvm_create_update.go
  core/steps/event/publish.go
  core/steps/event/publish_test.go
  core/steps/microvm/create.go
  core/steps/microvm/create_test.go
  core/steps/microvm/delete.go
  core/steps/microvm/delete_test.go
  core/steps/microvm/start.go
  core/steps/microvm/start_test.go
  core/steps/network/interface_create.go
  core/steps/network/interface_create_test.go
  core/steps/network/interface_delete.go
  core/steps/network/interface_delete_test.go
  core/steps/runtime/dir_create.go
  core/steps/runtime/dir_create_test.go
  core/steps/runtime/dir_delete.go
  core/steps/runtime/dir_delete_test.go
  core/steps/runtime/initrd_mount.go
  core/steps/runtime/initrd_mount_test.go
  core/steps/runtime/kernel_mount.go
  core/steps/runtime/kernel_mount_test.go
  core/steps/runtime/repo_release.go
  core/steps/runtime/repo_release_test.go
  core/steps/runtime/volume_mount.go
  core/steps/runtime/volume_mount_test.go
  go.mod
  go.sum
  infrastructure/controllers/microvm_controller.go
  pkg/planner/actuator.go
  pkg/planner/actuator_test.go
  pkg/planner/planner.go
Labels: kind/feature

#271 refactor: apply opinionated api defaults based on accepted adr
  api/services/microvm/v1alpha1/microvms.swagger.json
  api/types/microvm.pb.go
  api/types/microvm.proto
  cmd/dev-helper/main.go
  core/application/app_test.go
  core/models/microvm.go
  core/models/network.go
  core/models/vmid.go
  core/models/vmid_test.go
  core/models/volumes.go
  core/plans/helper_test.go
  core/plans/microvm_create_update.go
  core/steps/runtime/volume_mount_test.go
  docs/adr/0241-opinionated-api-changes.md
  infrastructure/firecracker/config.go
  infrastructure/grpc/convert.go
  infrastructure/grpc/defaults.go
  pkg/defaults/defaults.go
  pkg/validation/validate.go
  pkg/validation/validate_test.go
  test/e2e/utils/utils.go
  userdocs/docs/grpc/types/proto.md
Labels: area/api, size/m, kind/refactor

#277 fix: MicroVM can't be deleted if it failed to create too many times
  core/application/commands.go
  hack/scripts/payload/CreateMicroVM.json
Labels: kind/bug, area/reconciliation

#269 Review OCI tests
  .github/workflows/test.yml
  Makefile
  infrastructure/containerd/client_interface.go
  infrastructure/containerd/event_service_test.go
  infrastructure/containerd/image_service.go
  infrastructure/containerd/image_service_integration_test.go
  infrastructure/containerd/image_service_test.go
  infrastructure/containerd/lease.go
  infrastructure/containerd/repo_test.go
  infrastructure/mock/containerd.go
  infrastructure/mock/ext_containerd.go
  infrastructure/mock/ext_containerd_leases.go
  infrastructure/mock/ext_containerd_snapshots.go
  infrastructure/mock/gen.go
  infrastructure/mock/ports.go
Labels: area/testing, kind/refactor

#282 fix: root volume mount host path
  infrastructure/firecracker/config.go
Labels: kind/bug

#278 feat(test): Write generated equinix keys to tempdir
  test/tools/README.md
  test/tools/config/config.py
  test/tools/config/schema.yaml
  test/tools/example-config.yaml
  test/tools/metal/welder.py
  test/tools/run.py
  test/tools/test/runner.py
Labels: kind/feature

#285 Ensure tests failure causes exit 1
  test/tools/test/runner.py
Labels: kind/bug, area/testing

#290 feat: Bootstrap Equinix machines with our new firecracker fork
  hack/scripts/bootstrap.sh
Labels: kind/feature

#293 refactor: update ListMessage to include full MicroVM type
  api/services/microvm/v1alpha1/microvms.pb.go
  api/services/microvm/v1alpha1/microvms.proto
  api/services/microvm/v1alpha1/microvms.swagger.json
  infrastructure/grpc/server.go
  userdocs/docs/grpc/services/microvm/v1alpha1/proto.md
Labels: area/api, kind/refactor, size/s

#294 test: add server tests and additional mocks
  infrastructure/grpc/server.go
  infrastructure/grpc/server_test.go
  infrastructure/mock/gen.go
  infrastructure/mock/ports.go
Labels: area/api, size/m, kind/cleanup

#288 feat: use configuration file to start firecracker
  cmd/dev-helper/main.go
  core/plans/microvm_create_update_test.go
  core/ports/services.go
  core/steps/microvm/start.go
  core/steps/microvm/start_test.go
  go.mod
  go.sum
  infrastructure/firecracker/config.go
  infrastructure/firecracker/create.go
  infrastructure/firecracker/provider.go
  infrastructure/firecracker/state.go
  infrastructure/firecracker/types.go
  infrastructure/mock/ports.go
  internal/command/flags/flags.go
  internal/config/config.go
  internal/inject/wire.go
  internal/inject/wire_gen.go
  pkg/defaults/defaults.go
Labels: kind/refactor, area/firecracker

#297 fix: remove socket check from e2e
  test/e2e/e2e_test.go
Labels: kind/bug, area/testing

#298 fix: wait for pidfile
  test/e2e/e2e_test.go
Labels: kind/bug, area/testing, size/xs
