Repository liquidmetal-dev/flintlock, pull requests merged in 2022-06, with the labels that each got.

#460 chore: Bump go to 1.18
  .github/workflows/deploy-docs.yaml
  .github/workflows/lint.yml
  .github/workflows/release.yml
  .github/workflows/test.yml
  .golangci.yml
  CONTRIBUTING.md
  go.mod
  go.sum
Labels: kind/feature

#446 fix: Allow fork action to open Issue
  .github/workflows/fork.yaml
Labels: kind/bug

#439 fix: Correct org name in nightly_e2e job
  .github/workflows/nightly_e2e.yml
Labels: kind/bug

#462 feat: Add (very) basic auth
  go.mod
  go.sum
  internal/command/flags/flags.go
  internal/command/run/run.go
  internal/config/config.go
  pkg/auth/basic.go
  pkg/auth/basic_test.go
  pkg/auth/errors.go
Labels: kind/feature

#467 chore(deps): Bump buf to 1.5.0
  Makefile
  api/services/microvm/v1alpha1/microvms.pb.go
  api/services/microvm/v1alpha1/microvms.pb.gw.go
  api/services/microvm/v1alpha1/microvms.swagger.json
  api/services/microvm/v1alpha1/microvms_grpc.pb.go
  api/types/microvm.pb.go
  buf.lock
  userdocs/yarn.lock
Labels: kind/bug

#471 refactor: remove unused mount point on drive
  api/services/microvm/v1alpha1/microvms.swagger.json
  api/types/microvm.pb.go
  api/types/microvm.proto
  buf.lock
  core/application/app_test.go
  core/models/volumes.go
  core/plans/helper_test.go
  core/steps/runtime/volume_mount_test.go
  hack/scripts/payload/CreateMicroVM.json
  infrastructure/grpc/convert.go
  infrastructure/grpc/server_test.go
  pkg/validation/validate_test.go
  test/e2e/utils/utils.go
  userdocs/docs/grpc/types/proto.md
Labels: area/api, kind/refactor

#464 feat: Add (m)TLS
  docs/quick-start.md
  hack/scripts/gen_local_certs.sh
  hack/scripts/send.sh
  internal/command/flags/flags.go
  internal/command/run/run.go
  internal/config/config.go
  internal/config/errors.go
  internal/config/validation.go
  internal/config/validation_test.go
  pkg/auth/tls.go
  test/e2e/utils/runner.go
Labels: kind/feature

#473 build: removed gh cli call from release workflow
  .github/workflows/release.yml
Labels: kind/refactor
