Repository liquidmetal-dev/flintlock, pull requests merged in 2022-09, with the labels that each got.

#535 Curl scripts to make Vagrantfile self-contained
  Vagrantfile
Labels: kind/feature

#522 feat: cloudhypervisor api client
  go.mod
  go.sum
  pkg/cloudhypervisor/client.go
  pkg/cloudhypervisor/handlers.go
  pkg/cloudhypervisor/types.go
Labels: kind/feature, area/cloud-hypervisor

#540 fix: Set address based on interface in provision.sh
  hack/scripts/provision.sh
Labels: kind/bug

#543 Add --bridge flag to flintlock provision script
  hack/scripts/provision.sh
Labels: kind/feature
