Repository liquidmetal-dev/flintlock, pull requests merged in 2022-02, with the labels that each got.

#357 feat: Expose firecracker metrics
  .github/workflows/release.yml
  .golangci.yml
  Makefile
  cmd/flintlock-metrics/main.go
  core/ports/services.go
  docs/quick-start.md
  go.mod
  go.sum
  hack/scripts/monitoring/metrics/docker-compose.yaml
  hack/scripts/monitoring/metrics/prometheus.yml
  hack/scripts/payload/CreateMicroVM.json
  infrastructure/firecracker/metrics.go
  infrastructure/firecracker/provider.go
  infrastructure/mock/ports.go
  internal/command/flags/urfave.go
  internal/command/metrics/main.go
  internal/command/metrics/serve.go
  internal/config/config.go
  userdocs/docs/getting-started/extras/metrics.md
Labels: kind/feature

#380 Better hack/send tooling
  hack/scripts/payload/DeleteMicroVM.json
  hack/scripts/payload/ListMicroVMs.json
  hack/scripts/send.sh
Labels: kind/refactor

#381 Fix the bump firecracker workflow
  .github/workflows/fork.yaml
  hack/scripts/bump_firecracker.sh
Labels: kind/bug, size/s

#385 fix: Match Firecracker 1.0.0 API
  infrastructure/firecracker/config.go
  infrastructure/firecracker/testdata/vm_config.json
  infrastructure/firecracker/types.go
Labels: kind/bug, area/firecracker

#386 Notify on issue creation only
  .github/workflows/fork.yaml
Labels: kind/bug, size/xs

#393 chore: rolling back Firecracker v1.0.0 changes
  infrastructure/firecracker/config.go
  infrastructure/firecracker/testdata/vm_config.json
  infrastructure/firecracker/types.go
Labels: kind/refactor

#389 feat: added grpc proxy dial option to client package
  Makefile
  client/go.mod
  client/go.sum
  client/grpc/proxy.go
Labels: kind/feature

#394 Set instance_id in flintlock
  client/cloudinit/cloudinit.go
  client/cloudinit/instance/const.go
  client/cloudinit/instance/metadata.go
  client/cloudinit/instance/metadata_test.go
  client/cloudinit/metadata.go
  client/cloudinit/network/network.go
  client/cloudinit/userdata/userdata.go
  client/go.mod
  core/application/app_test.go
  core/application/commands.go
  go.mod
  go.sum
  infrastructure/firecracker/config.go
  infrastructure/grpc/convert.go
Labels: kind/feature

#395 Note how to override component versions
  hack/scripts/README.md
Labels: kind/documentation, size/xs

#401 Pin firecracker to `v0.25.2-macvtap` for nightly e2es
  test/e2e/utils/runner.go
  test/tools/config/userdata.sh
Labels: kind/bug, area/testing
