Repository liquidmetal-dev/flintlock, pull requests merged in 2022-01, with the labels that each got.

#342 Use ubuntu_20_04 for e2e devices
  hack/scripts/bootstrap.sh
  test/tools/config/config.py
  test/tools/config/userdata.sh
  test/tools/example-config.yaml
Labels: kind/bug, area/testing

#345 feat: bind flintlock server to internal ip
  flintlockd.service
  hack/scripts/README.md
  hack/scripts/provision.sh
Labels: kind/feature

#344 Set ordered names for guest devices
  api/services/microvm/v1alpha1/microvms.swagger.json
  api/types/microvm.pb.go
  api/types/microvm.proto
  go.mod
  go.sum
  infrastructure/grpc/convert.go
  infrastructure/grpc/defaults.go
  infrastructure/grpc/server_test.go
  infrastructure/mock/ports.go
  test/e2e/utils/utils.go
  userdocs/docs/grpc/types/proto.md
Labels: kind/feature

#346 fix: ensure we use the snapshot for the highest image layer
  infrastructure/containerd/image_service.go
Labels: kind/bug

#349 feat: exposing bootcmd cloud-init option
  client/cloudinit/userdata.go
Labels: kind/feature

#352 chore: flintlock dependency updates
  Makefile
  api/services/microvm/v1alpha1/microvms.pb.go
  api/types/microvm.pb.go
  buf.lock
  buf.yaml
  go.mod
  go.sum
  internal/command/gw/gw.go
  userdocs/package-lock.json
  userdocs/package.json
  userdocs/yarn.lock
Labels: dependencies, kind/cleanup

#341 Exit 1 if installing apt packages fails
  hack/scripts/provision.sh
Labels: kind/bug

#355 Update the service file to use config.yaml
  config.yaml.example
  flintlockd.service
  hack/scripts/README.md
  hack/scripts/provision.sh
Labels: kind/feature

#320 feat: Change API to use Additional Kernel Args
  .golangci.yml
  api/services/microvm/v1alpha1/microvms.swagger.json
  api/types/microvm.pb.go
  api/types/microvm.proto
  core/models/kernel.go
  core/models/microvm.go
  hack/scripts/payload/CreateMicroVM.json
  infrastructure/firecracker/config.go
  infrastructure/firecracker/testdata/vm_config.json
  internal/config/kernel_cmd_line.go
  test/e2e/utils/utils.go
  userdocs/docs/grpc/types/proto.md
Labels: kind/feature

#359 fix: remove the `imageExists` check before Pull
  infrastructure/containerd/image_service.go
  infrastructure/containerd/image_service_test.go
Labels: kind/bug

#361 feat: Make create return full Microvm object
  api/services/microvm/v1alpha1/microvms.pb.go
  api/services/microvm/v1alpha1/microvms.proto
  api/services/microvm/v1alpha1/microvms.swagger.json
  buf.lock
  infrastructure/grpc/convert.go
  infrastructure/grpc/server.go
  infrastructure/grpc/server_test.go
  test/e2e/e2e_test.go
  userdocs/docs/grpc/services/microvm/v1alpha1/proto.md
Labels: kind/feature

#366 chore: update nightly e2e slack messages
  .github/workflows/nightly_e2e.yml
Labels: kind/documentation

#327 feat: Use flintlock unique id
  api/events/spec.go
  api/services/microvm/v1alpha1/microvms.pb.go
  api/services/microvm/v1alpha1/microvms.pb.gw.go
  api/services/microvm/v1alpha1/microvms.proto
  api/services/microvm/v1alpha1/microvms.swagger.json
  api/types/microvm.pb.go
  api/types/microvm.proto
  core/application/app_test.go
  core/application/commands.go
  core/application/errors.go
  core/application/query.go
  core/application/reconcile.go
  core/errors/errors.go
  core/models/vmid.go
  core/models/vmid_test.go
  core/plans/helper_test.go
  core/plans/microvm_create_update_test.go
  core/plans/microvm_delete.go
  core/plans/microvm_delete_test.go
  core/ports/repositories.go
  core/ports/usecases.go
  core/steps/event/publish_test.go
  core/steps/microvm/create_test.go
  core/steps/microvm/delete_test.go
  core/steps/microvm/start_test.go
  core/steps/network/interface_create_test.go
  core/steps/network/interface_delete_test.go
  core/steps/network/testconst_test.go
  core/steps/runtime/initrd_mount_test.go
  core/steps/runtime/kernel_mount_test.go
  core/steps/runtime/repo_release.go
  core/steps/runtime/repo_release_test.go
  core/steps/runtime/volume_mount_test.go
  hack/scripts/payload/DeleteMicroVM.json
  infrastructure/containerd/content.go
  infrastructure/containerd/image_service_integration_test.go
  infrastructure/containerd/repo.go
  infrastructure/containerd/repo_test.go
  infrastructure/controllers/microvm_controller.go
  infrastructure/controllers/microvm_controller_test.go
  infrastructure/firecracker/provider.go
  infrastructure/firecracker/state.go
  infrastructure/grpc/convert.go
  infrastructure/grpc/server.go
  infrastructure/grpc/server_test.go
  infrastructure/mock/ports.go
  test/e2e/e2e_test.go
  test/e2e/utils/utils.go
  userdocs/docs/grpc/services/microvm/v1alpha1/proto.md
  userdocs/docs/grpc/types/proto.md
Labels: kind/feature

#367 fix: uid related issues
  core/application/app_test.go
  core/application/commands.go
  infrastructure/containerd/repo.go
  test/e2e/e2e_test.go
Labels: kind/bug, size/xs

#369 feat: ability to list microvms based on name
  api/services/microvm/v1alpha1/microvms.pb.go
  api/services/microvm/v1alpha1/microvms.pb.gw.go
  api/services/microvm/v1alpha1/microvms.proto
  api/services/microvm/v1alpha1/microvms.swagger.json
  buf.lock
  core/application/app_test.go
  core/application/errors.go
  core/application/query.go
  core/application/reconcile.go
  core/models/microvm.go
  core/ports/repositories.go
  core/ports/usecases.go
  go.mod
  go.sum
  infrastructure/containerd/repo.go
  infrastructure/containerd/repo_test.go
  infrastructure/grpc/server.go
  infrastructure/mock/ports.go
  test/e2e/e2e_test.go
  test/e2e/utils/utils.go
  userdocs/docs/grpc/services/microvm/v1alpha1/proto.md
Labels: kind/feature, area/api, size/m
