Repository liquidmetal-dev/flintlock, pull requests merged in 2022-08, with the labels that each got.

#495 Update quickstart firecracker notes
  docs/quick-start.md
Labels: kind/documentation

#496 fix: Pin containerd to 1.6.6
  test/tools/config/userdata.sh
Labels: kind/bug

#504 feat: add pprof to flintlock
  internal/command/flags/flags.go
  internal/command/run/run.go
  internal/config/config.go
Labels: kind/feature

#507 feat: add support for Firecracker v1+
  README.md
  infrastructure/firecracker/config.go
  infrastructure/firecracker/types.go
Labels: kind/feature

#511 chore: remove pinning of the firecracker version
  test/tools/config/userdata.sh
Labels: kind/refactor

#517 Update fc build instruction to be more useful
  .github/workflows/fork.yaml
Labels: kind/documentation

#514 refactor: move validation/defaults to app
  core/application/app_test.go
  core/application/commands.go
  infrastructure/grpc/convert.go
  infrastructure/grpc/defaults.go
  infrastructure/grpc/server.go
Labels: kind/refactor

#521 refactor: moved resync to controller
  core/application/reconcile.go
  core/ports/usecases.go
  infrastructure/controllers/microvm_controller.go
  infrastructure/controllers/microvm_controller_test.go
  internal/inject/wire.go
  internal/inject/wire_gen.go
Labels: kind/refactor, area/reconciliation

#519 feat: force dhcp to use mac as client identifier
  client/cloudinit/network/network.go
  infrastructure/firecracker/config.go
Labels: kind/feature
