Repository liquidmetal-dev/flintlock, pull requests merged in 2024-07, with the labels that each got.

#849 chore: update readme with notice
  COPYRIGHT.md
  README.md
  hack/boilerplate.generatego.txt
Labels: kind/chore

#861 docs: update readme and contributing guide
  CONTRIBUTING.md
  MAINTAINERS
  README.md
Labels: kind/documentation

#865 chore: update stale bot to not close issues
  .github/workflows/stale.yml
Labels: kind/chore

#806 adding provider to convert
  infrastructure/grpc/convert.go
Labels: kind/bug, lifecycle/stale

#867 chore: remove 3rd party bundler
  .github/dependabot.yml
  .github/workflows/dependabot_bundler.yml
Labels: kind/chore, area/dependencies

#905 fix: docs publish workflows
  .github/workflows/deploy-docs.yaml
  .github/workflows/test-docs.yaml
  Makefile
  api/services/microvm/v1alpha1/microvms.pb.go
  api/services/microvm/v1alpha1/microvms.pb.gw.go
  api/services/microvm/v1alpha1/microvms.swagger.json
  api/types/microvm.pb.go
  api/types/microvm.swagger.json
  userdocs/package-lock.json
  userdocs/yarn.lock
Labels: kind/documentation

#913 Docs workflow
  .github/workflows/deploy-docs.yaml
  .github/workflows/test-docs.yaml
  userdocs/package-lock.json
  userdocs/package.json
  userdocs/yarn.lock
Labels: kind/documentation

#914 Update deploy-docs.yaml
  .github/workflows/deploy-docs.yaml
Labels: kind/documentation

#920 fix: cloud hypervisor auto starts
  core/errors/errors.go
  infrastructure/microvm/cloudhypervisor/provider.go
Labels: kind/bug, area/cloud-hypervisor
